### ISSUE TITLE
Todo list for Release 0.7.0

### ISSUE THREAD

**Issue by Thrameos** [jpype-project/jpype#371]
Items that need to be completed

- [x] Update docs to contain latest API.
- [x] Complete primitive duck work so that numpy types are properly handled.
- [x] Complete numpy array so that conversions to an from numpy work properly.
- [ ] Add jpype.compiler front end to match the new docs.
- [x] Add proxy front end using annotations.
- [x] Fix appveyor so we have windows CI.

I think that about covers it.

**Comment by rapgro** [comment]
Support for Python 3.7, #332

**Comment by rapgro** [comment]
@marscher No idea at the moment. I'll test with 3.7.1 with the removal of the build for python 2.7 as officially requested for Fedora.

**Comment by Thrameos** [comment]
Two more api issues left and a documentation issue.  Anyone have anything else that is a must do for a 0.7.0 release?

**Comment by rbprogrammer** [comment]
I realize there's only a few items left before a 0.7.0 version gets released, but since this ticket has been open for 5+ months would someone be able to either implement those changes and release 0.7.0 or could we release a 0.6.4 version now?

I ask because my company needs the updated code (has some bug fixes we need) but it's kind of a faff installing a non-official versioned release.

**Comment by Thrameos** [comment]
Yeah this should really happen.  Unfortunately, job duties have dragged me in other directions due to loss of a my key programmer.  As a government employee working for the current administration, my budget at work is cut so badly all of the projects that required use of Jpype are on hold for the last few months, and a water leak took out the floor of my upstairs bathroom eating all my other free time.  Once I have a budget again, I can hire the required replacement staff and get those projects back in motion pushing this back to the top of the list, though it has been any week now for the last two months.  I will see if I can make some time in the near term.

I also need to find the time to get Jpype to run on Java 9-current as Java8 is falling off pace with current JDK releases.

**Comment by Thrameos** [comment]
Fixed with #427
